### PR TITLE
Multiarch docker image build

### PR DESCRIPTION
**Pull request by akatona84**
## Description

Mutliarch docker image build of kafka-operator.

https://github.com/banzaicloud/koperator/issues/1058

## Type of Change

- ~Bug Fix~
- [x] New Feature
- ~Breaking Change~
- ~Refactor~
- ~Documentation~
- [x] Other : build enhancement

## Checklist

- [x] I have read the [contributing guidelines](../CONTRIBUTING.md)
- [x] Existing issues have been referenced (where applicable)
- [x] I have verified this change is not present in other open pull requests

### CODE REVIEW

**Review by pregnor — APPROVED** [review]
LGTM

@akatona84 thanks for the contribution, please sign the CLA or click recheck if you already did.

CC: @chrisgacsal @bartam1

**Comment by pregnor** [comment]
Note: I edited the description to remove unchecked boxes so Mergable would be satisfied.

**Review by bartam1 — APPROVED** [review]
LGTM!

**Comment by akatona84** [comment]
What else is needed to submit this?

**Pull request merged**
