### PR TITLE
Upgrade istio to 1.15.0

### PR DESCRIPTION
**Pull request by nishantapatil3**
| Q               | A      |
| --------------- | ------ |
| Bug fix?        | no|
| New feature?    | yes |
| API breaks?     | no |
| Deprecations?   | no |
| License         | Apache 2.0 |

### What's in this PR?
Upgrade istio-1.13 to istio-1.15

### Why?
To support the latest istio-1.15 on koperator

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)

## Tests
```
=== RUN   TestControllers
Running Suite: Controller Suite
===============================
Random Seed: 1663175832
Will run 16 of 16 specs

W0914 10:17:16.363165   68666 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0914 10:17:16.365761   68666 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
••••••••••••••••
Ran 16 of 16 Specs in 81.320 seconds
SUCCESS! -- 16 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestControllers (81.32s)
PASS
coverage: [no statements]
ok  	github.com/banzaicloud/koperator/controllers/tests	83.327s	coverage: [no statements]
=== RUN   TestControllersWithClusterRegistry
Running Suite: Controller Suite with Cluster Registry
=====================================================
Random Seed: 1663175832
Will run 8 of 8 specs

W0914 10:17:16.423725   68665 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0914 10:17:16.425770   68665 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
••••••••
Ran 8 of 8 Specs in 66.528 seconds
SUCCESS! -- 8 Passed | 0 Failed | 0 Pending | 0 Skipped
```

### CODE REVIEW

**Review by panyuenlau — COMMENTED** [review]
LGTM. 

I am curious if this has been tested with a kafka cluster is accessible from outside of the Kubernetes cluster via external listener using Istio ingress? 

See [this part](https://github.com/banzaicloud/koperator/blob/master/config/samples/kafkacluster-with-istio.yaml#L57-L61) regarding how the external listeners can be created for testing

> Note: the external listener part is not covered with the current tests that we have

**Review by bartam1 — APPROVED** [review]
LGTM, I forgot to put length check in the test. I have fixed it.

**Review by pregnor — APPROVED** [review]
LGTM

**Comment by pregnor** [comment]
Please wait for either @panyuenlau or @hi-im-aren 's approval as well to have proper +2.

**Comment by nishantapatil3** [comment]
Thanks @panyuenlau @hong6914 , for helping me and testing external listeners, PASS!
```
kcat -b a281d7351225e4546a0d2b5289a94f3e-1977502687.us-west-2.elb.amazonaws.com:29092 -t kafkacat-topic -X enable.ssl.certificate.verification=false -L -v
Metadata for kafkacat-topic (from broker -1: a281d7351225e4546a0d2b5289a94f3e-1977502687.us-west-2.elb.amazonaws.com:29092/bootstrap):
 3 brokers:
  broker 0 at a281d7351225e4546a0d2b5289a94f3e-1977502687.us-west-2.elb.amazonaws.com:19095
  broker 2 at a281d7351225e4546a0d2b5289a94f3e-1977502687.us-west-2.elb.amazonaws.com:19097
  broker 1 at a281d7351225e4546a0d2b5289a94f3e-1977502687.us-west-2.elb.amazonaws.com:19096 (controller)
 1 topics:
  topic "kafkacat-topic" with 1 partitions:
    partition 0, leader 0, replicas: 0, isrs: 0 
```

**Review by panyuenlau — APPROVED** [review]

**Pull request merged**
