### PR TITLE
Move Helm chart CRDs to a dedicated folder

### PR DESCRIPTION
**Pull request by rappizs**
## Description:

Fixes https://github.com/banzaicloud/koperator/issues/1034

Solution details: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you
Note that CRDs will be installed by default, it can be turned off with the `--skip-crds` flag for `helm install`.

## Type of Change

- [x] Refactor

## Checklist

- [x] I have read the [contributing guidelines](../CONTRIBUTING.md)
- [x] Existing issues have been referenced (where applicable)
- [x] I have verified this change is not present in other open pull requests
- [x] All code style checks pass
- [x] All new and existing tests pass

### CODE REVIEW

**Review by pregnor — APPROVED** [review]
LGTM, please double check the release CI to be able to work with the modifications: https://github.com/banzaicloud/koperator/blob/master/.github/workflows/release.yml.

It looked okay to me, but take a look yourself as well.

Edit: also see Darren's comment.

**Comment by rappizs** [comment]
> please double check the release CI to be able to work with the modifications

Works fine, it uses the manifests from `config/base/crds`.

**Review by panyuenlau — APPROVED** [review]
LGTM!

**Review by pregnor — APPROVED** [review]
FYI this will be a breaking change in the chart version because we remove a field.

**Pull request merged**
