### PR TITLE
Added imagePullSecrets to deployment template

### PR DESCRIPTION
**Pull request by Kuvesz**
| Q               | A      |
| --------------- | ------ |
| Bug fix?        | yes |
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| License         | Apache 2.0 |

### What's in this PR?
I added imagePullSecrets to the deployment template and updated the chart version. Also updated release.yml to not include dev tags for now in releases.

### Why?
Not sure when there would be a need for this as the images are publicly accessible but just in case it doesn't hurt if it's there.

### Checklist
- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline

### CODE REVIEW

**Review by pregnor — COMMENTED** [review]
The change itself looks okay even though I would argue we should add commented out example code into the `values.yaml`.

The only use-case I could come up with would possibly be an air-gapped system with access control over the images.
I'm hesitant to approve, because I don't want additional unused code in the code base, but also don't want to block progress or uniforming things.

**Comment by Kuvesz** [comment]
> The change itself looks okay even though I would argue we should add commented out example code into the `values.yaml`.
> 
> The only use-case I could come up with would possibly be an air-gapped system with access control over the images. I'm hesitant to approve, because I don't want additional unused code in the code base, but also don't want to block progress or uniforming things.

To be honest I'm not exactly sure we need this either as I've stated in my original comment. Everything else will be fine without it really and we can come back to this if someone from the community feels like they need it?

**Review by pregnor — DISMISSED** [review]

**Comment by pregnor** [comment]
We can let it fly as the values.yaml already contains the corresponding config.

**Review by bartam1 — CHANGES_REQUESTED** [review]
I think we can remove this part after that change:
https://github.com/banzaicloud/koperator/blob/c30ef4c02685fd79ed8fcba6cbe337acf3715ad0/charts/kafka-operator/templates/operator-rbac.yaml#L4

**Comment by Kuvesz** [comment]
> I think we can remove this part after that change:
> 
> https://github.com/banzaicloud/koperator/blob/c30ef4c02685fd79ed8fcba6cbe337acf3715ad0/charts/kafka-operator/templates/operator-rbac.yaml#L4

I don't quite get why? Would you mind explaining it a bit further?

**Comment by bartam1** [comment]
> > I think we can remove this part after that change:
> > https://github.com/banzaicloud/koperator/blob/c30ef4c02685fd79ed8fcba6cbe337acf3715ad0/charts/kafka-operator/templates/operator-rbac.yaml#L4
> 
> I don't quite get why? Would you mind explaining it a bit further?

When you add an imagepullsecret into a serviceaccount then a pod which use that serviceaccount will contain the imagepullsecret what is in the serviceaccount. Here you add that imagepullsecret into the deployment anyway. Our serviceaccount imagepullsecret solution is wrong I think because when a user disable (https://github.com/banzaicloud/koperator/blob/c30ef4c02685fd79ed8fcba6cbe337acf3715ad0/charts/kafka-operator/values.yaml#L73) the serviceaccount creation then the imagepullsecret will not be in the default serviceaccount and in the  koperator's pod.

**Review by pregnor — APPROVED** [review]

**Pull request merged**
