### PR TITLE
Upgrade PodDisruptionBudget API to v1

### PR DESCRIPTION
**Pull request by amuraru**
| Q               | A      |
| --------------- | ------ |
| Bug fix?        | no |
| New feature?    | yes |
| API breaks?     | no |
| Deprecations?   | no |
| License         | Apache 2.0 |

### What's in this PR?

Upgrade PodDisruptionBudget API to v1 

### Why?

Relying on newly stable APIs

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)

### CODE REVIEW

**Review by Kuvesz — DISMISSED** [review]
LGTM, thanks for the update! :)

**Review by hi-im-aren — APPROVED** [review]

**Review by panyuenlau — CHANGES_REQUESTED** [review]
LGTM, but please hold until the official release (v0.22.0) is out before merging the PR due to this comment https://github.com/banzaicloud/koperator/pull/864#pullrequestreview-1112127906 - we expect to drop the release next week

**Review by panyuenlau — APPROVED** [review]
Mergable now. Again, apologize for the inconvenience

**Review by pregnor — APPROVED** [review]

**Review by hi-im-aren — APPROVED** [review]

**Comment by pregnor** [comment]
Thank you again for the contribution Adrian.

**Pull request merged**
