### PR TITLE
Upgrade PodDisruptionBudget API to v1

### PR DESCRIPTION
**Pull request by amuraru**
| Q               | A      |
| --------------- | ------ |
| Bug fix?        | no |
| New feature?    | no |
| API breaks?     | yes |
| Deprecations?   | yes |
| License         | Apache 2.0 |

### What's in this PR?

Upgrade PodDisruptionBudget API to v1.
This requires k8s 1.21

### Why?

Keeping up to do with currently maintained K8s versions and removing old deprecated API.

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)

### CODE REVIEW

**Review by panyuenlau — APPROVED** [review]

**Review by bartam1 — APPROVED** [review]

**Review by pregnor — COMMENTED** [review]
The `PodDisruptionBudget` API `v1beta1` APIVersion is just deprecated, but not disabled until K8s version 1.25+ .

[Currently](https://github.com/banzaicloud/koperator-docs/blob/master/docs/install-kafka-operator.md) we are supporting pre-1.21 K8s versions as well where `PodDisruptionBudget` API `v1` is not available.

We are planning to upgrade the supported K8s versions to [latest-2;latest] in the near future, but until our minimum supported K8s version is 1.21, I would do this change yet in order to fulfill the contract regarding currently supported version.

**Review by bartam1 — APPROVED** [review]

**Comment by pregnor** [comment]
Sorry Adrian, this was an accidental merge.

We will revert the PR for now with #885, because we expect to bump the charts and tag 0.22.0 next week that should still happen without this change and then merge this PR into master after 0.22.0 is tagged ETA next week.

**Comment by pregnor** [comment]
@amuraru We have to choose between 2 approaches, either 
A, you merge the current banzaicloud/koperator:master into amuraru/koperator:pdb1 and push it - because we don't have write access to your fork - or 
B, we cherry-pick your commit over into a new PR opened targeting banzaicloud/koperator:master,
which would you prefer?

P.S.: once again, apologies for the extra hussle.

**Comment by amuraru** [comment]
No worries folks - I filed a new PR here: https://github.com/banzaicloud/koperator/pull/888

**Comment by pregnor** [comment]
Thanks

**Pull request merged**
